### ISSUE TITLE
Back layer is not visible on Mobile Firefox

### ISSUE THREAD

**Issue by azhdarchidArchon** [vega-spica/Personality-Sneak-Peek-Expanded#1]
![image](https://github.com/vega-spica/Personality-Sneak-Peek-Expanded/assets/105704165/760b298a-b6a6-4882-8848-8dcb29cc5374)

This issue remains even switching to the Desktop site.
![image](https://github.com/vega-spica/Personality-Sneak-Peek-Expanded/assets/105704165/0a02ffe6-6bc2-418a-96a8-740cad1e6d4a)

**Device**: Samsung Galaxy A31
**Browser**: Firefox 121.0

On the same device I viewed the site through **Chrome** and **Firefox Focus** with no problems. **Firefox Beta** has the same problem. On desktop, Firefox has no problems.

BTW, your tool is a lifesaver. I can barely see what personalities look like through the cosmic album.

**Comment by vega-spica** [comment]
hey, sorry for the inconvenience. this site is not exactly very... mobile friendly, in a few different ways.

can show me as to how an adult dragon displays on the dvc land website for the browser you are having issues with? this one, for example: https://dragon.dvc.land/view/kr?id=6527224096cb0f7db7e34c11

a screenshot would be most helpful, but if it's too inconvenient, you can describe to me whether or not the back and front of the auras both load, and as to whether or not the dragon fully fits within the canvas. if you could also try enabling (or disabling) "desktop view" on both sites and let me know if there any difference (better or worse), i would also appreciate it.

thanks for the report.

**Comment by vega-spica** [comment]
ah, that is quite different... i seem to have difficulty replicating the issue, as mobile Firefox (121.0.1) on my device (Xiaomi Poco X3 NFC) generates the front and back as intended on both mobile and desktop mode, as well as in a private tab.

![Screenshot_2024-01-04-13-02-22-816_org mozilla firefox](https://github.com/vega-spica/Personality-Sneak-Peek-Expanded/assets/63138880/13cc0816-e642-4ee1-b746-6f5ef13c5bd3)
![Screenshot_2024-01-04-13-01-59-088_org mozilla firefox](https://github.com/vega-spica/Personality-Sneak-Peek-Expanded/assets/63138880/07623c9e-f18b-40c1-b763-016c4170fe83)

i do intend to do some adjustments to how the images are generated, as well as the media queries. it may or may not happen to resolve this issue, but i will note that the tool will not necessarily work for every device and browser in the end, especially mobile ones. regardless, i will ask around to see if people with different devices can replicate this.

thanks for the report.
